### ISSUE TITLE
Plots are sized in the plotly json data, so indication 100% width does not work.

### ISSUE THREAD

**Issue by sballe73** [MieuxVoter/majority-judgment-tracker#38]
![image](https://user-images.githubusercontent.com/8128986/162136677-0183fe06-e77b-48ce-9232-d7b54a2845fa.png)
example from a opinion way combo graph.
Once specified in the file the size does superseed what is indicated in react :
![image](https://user-images.githubusercontent.com/8128986/162136850-775901d3-8343-42c0-ba96-9f5572ca70c7.png)
remove it and it becomes applied : 
![image](https://user-images.githubusercontent.com/8128986/162136935-929b9738-9e78-4a06-a58c-9cd61efae7b9.png)

**Comment by Ipuch** [comment]
#41 resolved
